ewz_recaptcha:
    public_key:      '%env(string:EWZ_RECAPTCHA_SITE_KEY)%'
    private_key:     '%env(string:EWZ_RECAPTCHA_SECRET)%'
    version:         3
    enabled:         true
    hide_badge:      false
    score_threshold: 0.6

when@dev:
    ewz_recaptcha:
        enabled: false
