framework:
    secret:               '%env(APP_SECRET)%'
    csrf_protection:      true
    http_method_override: false
    esi:                  true
    fragments:            true
    session:
        enabled:            true
        handler_id:         null
        cookie_lifetime:    0
        cookie_secure:      'auto'
        cookie_samesite:    'lax'
        storage_factory_id: 'session.storage.factory.native'
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: 'session.storage.factory.mock_file'
