# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session:
        name:            '%app_cookie_session_name%'
        handler_id:      null
        cookie_secure:   auto
        cookie_samesite: lax
        cookie_lifetime: 31536000 # 1 year
    php_errors:
        log: true
