liip_imagine:
    driver: 'gd'
    loaders:
        default:
            filesystem:
                locator: filesystem_insecure
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        2400xY:
            quality: 75
            filters:
                thumbnail: { size: [ 2400, null ], mode: outbound }
        1200xY:
            quality: 85
            filters:
                thumbnail: { size: [ 1200, null ], mode: outbound }
        600xY:
            quality: 95
            filters:
                thumbnail: { size: [ 600, null ], mode: outbound }
        348x232:
            quality: 100
            filters:
                thumbnail: { size: [ 348, 232 ], mode: outbound }
        300xY:
            quality: 100
            filters:
                thumbnail: { size: [ 300, null ], mode: outbound }
