twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@EWZRecaptcha/Form/ewz_recaptcha_widget.html.twig'
    globals:
        locale:                    '%locale%'
        front_web_title:           '%front_web_title%'
        front_web_phone:           '%front_web_phone%'
        front_web_address:         '%front_web_address%'
        front_web_postal_code:     '%front_web_postal_code%'
        front_web_city:            '%front_web_city%'
        front_web_province:        '%front_web_province%'
        front_legal_id_tax_number: '%front_legal_id_tax_number%'
        front_legal_name:          '%front_legal_name%'
        front_legal_phone:         '%front_legal_phone%'
        front_legal_email:         '%front_legal_email%'
        front_legal_address:       '%front_legal_address%'
        front_legal_postal_code:   '%front_legal_postal_code%'
        front_legal_city:          '%front_legal_city%'
        front_legal_province:      '%front_legal_province%'
        front_base_url:            '%front_base_url%'
        google_analytics_enabled:  '%google_analytics_enabled%'
        google_analytics_code:     '%google_analytics_code%'
        mailer_destination:        '%mailer_destination%'
        app_cookie_session_name:   '%app_cookie_session_name%'
        enable_cookies_consent:    true
