vich_uploader:
    db_driver: orm
    mappings:
        blog:
            uri_prefix: '/uploads'
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'slug'}
